-- Module 6: Attendance. One record per employee per day. Wi-Fi/IP capture (no GPS).
-- Columns match AttendanceRecord + BaseEntity (Hibernate ddl-auto=validate).

CREATE TABLE attendance_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT       NOT NULL,
    attendance_date  DATE         NOT NULL,
    attendance_type  VARCHAR(30)  NOT NULL,
    source           VARCHAR(20)  NOT NULL,
    clock_in         TIMESTAMPTZ,
    clock_out        TIMESTAMPTZ,
    working_minutes  INTEGER,
    late             BOOLEAN      NOT NULL DEFAULT FALSE,
    half_day         BOOLEAN      NOT NULL DEFAULT FALSE,
    ip_address       VARCHAR(45),
    device_info      VARCHAR(255),
    browser_info     VARCHAR(255),
    wfh_reason       VARCHAR(300),
    work_location    VARCHAR(150),
    expected_hours   INTEGER,
    approval_status  VARCHAR(20)  NOT NULL DEFAULT 'NOT_REQUIRED',
    approved_by      VARCHAR(100),
    approved_at      TIMESTAMPTZ,
    remarks          VARCHAR(300),
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    version          BIGINT       NOT NULL DEFAULT 0,
    is_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT uk_attendance_emp_date UNIQUE (employee_id, attendance_date),
    CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_attendance_employee ON attendance_records (employee_id);
CREATE INDEX idx_attendance_date     ON attendance_records (attendance_date);
