-- Module 7: Leave Management. Configurable leave types, per-employee balances, and requests.
-- Columns match the entities + BaseEntity (Hibernate ddl-auto=validate).

CREATE TABLE leave_types (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(40)  NOT NULL,
    name                 VARCHAR(120) NOT NULL,
    description          VARCHAR(255),
    default_annual_quota INTEGER      NOT NULL DEFAULT 0,
    paid                 BOOLEAN      NOT NULL DEFAULT TRUE,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,
    created_by           VARCHAR(100),
    updated_by           VARCHAR(100),
    version              BIGINT       NOT NULL DEFAULT 0,
    is_deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT uk_leave_types_code UNIQUE (code),
    CONSTRAINT uk_leave_types_name UNIQUE (name)
);

CREATE TABLE leave_balances (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL,
    leave_type_id BIGINT       NOT NULL,
    year          INTEGER      NOT NULL,
    allocated     NUMERIC(6,1) NOT NULL DEFAULT 0,
    used          NUMERIC(6,1) NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    version       BIGINT       NOT NULL DEFAULT 0,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT uk_leave_balance_emp_type_year UNIQUE (employee_id, leave_type_id, year),
    CONSTRAINT fk_leave_balance_employee FOREIGN KEY (employee_id)   REFERENCES employees (id)   ON DELETE CASCADE,
    CONSTRAINT fk_leave_balance_type     FOREIGN KEY (leave_type_id) REFERENCES leave_types (id)
);

CREATE TABLE leave_requests (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         BIGINT       NOT NULL,
    leave_type_id       BIGINT       NOT NULL,
    from_date           DATE         NOT NULL,
    to_date             DATE         NOT NULL,
    days                NUMERIC(6,1) NOT NULL,
    half_day            BOOLEAN      NOT NULL DEFAULT FALSE,
    reason              VARCHAR(500),
    status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    manager_approved_by VARCHAR(190),
    manager_approved_at TIMESTAMPTZ,
    hr_approved_by      VARCHAR(190),
    hr_approved_at      TIMESTAMPTZ,
    decision_remarks    VARCHAR(300),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    version             BIGINT       NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id)   REFERENCES employees (id)   ON DELETE CASCADE,
    CONSTRAINT fk_leave_requests_type     FOREIGN KEY (leave_type_id) REFERENCES leave_types (id)
);
CREATE INDEX idx_leave_requests_employee ON leave_requests (employee_id);
CREATE INDEX idx_leave_requests_status   ON leave_requests (status);
