-- Module 8: Holiday Management. Columns match the Holiday entity + BaseEntity (ddl-auto=validate).

CREATE TABLE holidays (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE         NOT NULL,
    name         VARCHAR(150) NOT NULL,
    type         VARCHAR(20)  NOT NULL,
    region       VARCHAR(100),
    description  VARCHAR(300),
    recurring    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    version      BIGINT       NOT NULL DEFAULT 0,
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT uk_holidays_date_name UNIQUE (holiday_date, name)
);
CREATE INDEX idx_holidays_date ON holidays (holiday_date);
