-- Module 9: Announcement Management. Columns match the Announcement entity + BaseEntity.

CREATE TABLE announcements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                VARCHAR(200)  NOT NULL,
    body                 VARCHAR(4000),
    category             VARCHAR(30)   NOT NULL,
    target_department_id BIGINT,
    publish_at           TIMESTAMPTZ,
    expires_at           TIMESTAMPTZ,
    published            BOOLEAN       NOT NULL DEFAULT FALSE,
    pinned               BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ   NOT NULL,
    updated_at           TIMESTAMPTZ   NOT NULL,
    created_by           VARCHAR(100),
    updated_by           VARCHAR(100),
    version              BIGINT        NOT NULL DEFAULT 0,
    is_deleted           BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT fk_announcements_department FOREIGN KEY (target_department_id) REFERENCES departments (id)
);
CREATE INDEX idx_announcements_published ON announcements (published);
CREATE INDEX idx_announcements_category  ON announcements (category);
