-- Module 10: Notification Center. Columns match the Notification entity + BaseEntity.

CREATE TABLE notifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id   BIGINT        NOT NULL,
    channel        VARCHAR(20)   NOT NULL DEFAULT 'IN_APP',
    title          VARCHAR(200)  NOT NULL,
    message        VARCHAR(1000),
    status         VARCHAR(20)   NOT NULL DEFAULT 'SENT',
    read_flag      BOOLEAN       NOT NULL DEFAULT FALSE,
    read_at        TIMESTAMPTZ,
    reference_type VARCHAR(60),
    reference_id   BIGINT,
    failure_reason VARCHAR(300),
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT        NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_recipient ON notifications (recipient_id);
CREATE INDEX idx_notifications_read      ON notifications (read_flag);
