-- Module 11: Salary & Compensation — salary revision history and generated payslips.
-- Earnings only (no statutory deductions per project-rules.md). Columns match the entities.

CREATE TABLE salary_structures (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT       NOT NULL,
    effective_from    DATE         NOT NULL,
    basic             NUMERIC(14,2) NOT NULL DEFAULT 0,
    hra               NUMERIC(14,2) NOT NULL DEFAULT 0,
    special_allowance NUMERIC(14,2) NOT NULL DEFAULT 0,
    bonus             NUMERIC(14,2) NOT NULL DEFAULT 0,
    incentives        NUMERIC(14,2) NOT NULL DEFAULT 0,
    other_allowances  NUMERIC(14,2) NOT NULL DEFAULT 0,
    gross_monthly     NUMERIC(14,2) NOT NULL DEFAULT 0,
    remarks           VARCHAR(300),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100),
    version           BIGINT       NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_salary_structures_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_salary_structures_employee ON salary_structures (employee_id);

CREATE TABLE payslips (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT       NOT NULL,
    period_year       INTEGER      NOT NULL,
    period_month      INTEGER      NOT NULL,
    basic             NUMERIC(14,2) NOT NULL DEFAULT 0,
    hra               NUMERIC(14,2) NOT NULL DEFAULT 0,
    special_allowance NUMERIC(14,2) NOT NULL DEFAULT 0,
    bonus             NUMERIC(14,2) NOT NULL DEFAULT 0,
    incentives        NUMERIC(14,2) NOT NULL DEFAULT 0,
    other_allowances  NUMERIC(14,2) NOT NULL DEFAULT 0,
    gross_pay         NUMERIC(14,2) NOT NULL DEFAULT 0,
    net_pay           NUMERIC(14,2) NOT NULL DEFAULT 0,
    status            VARCHAR(20)  NOT NULL DEFAULT 'GENERATED',
    generated_at      TIMESTAMPTZ  NOT NULL,
    storage_key       VARCHAR(400),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100),
    version           BIGINT       NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT uk_payslips_emp_period UNIQUE (employee_id, period_year, period_month),
    CONSTRAINT fk_payslips_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_payslips_employee ON payslips (employee_id);
