-- Module 12: Reimbursement. Columns match the ReimbursementClaim entity + BaseEntity.

CREATE TABLE reimbursement_claims (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         BIGINT        NOT NULL,
    category            VARCHAR(20)   NOT NULL,
    amount              NUMERIC(12,2) NOT NULL,
    expense_date        DATE          NOT NULL,
    description         VARCHAR(500),
    bill_document_id    BIGINT,
    status              VARCHAR(20)   NOT NULL DEFAULT 'SUBMITTED',
    manager_decision_by VARCHAR(190),
    manager_decision_at TIMESTAMPTZ,
    finance_decision_by VARCHAR(190),
    finance_decision_at TIMESTAMPTZ,
    decision_remarks    VARCHAR(300),
    paid_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL,
    updated_at          TIMESTAMPTZ   NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    version             BIGINT        NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_reimbursements_employee FOREIGN KEY (employee_id)      REFERENCES employees (id) ON DELETE CASCADE,
    CONSTRAINT fk_reimbursements_document FOREIGN KEY (bill_document_id) REFERENCES documents (id)
);
CREATE INDEX idx_reimbursements_employee ON reimbursement_claims (employee_id);
CREATE INDEX idx_reimbursements_status   ON reimbursement_claims (status);
