-- Module 13: Confirmation & Probation. Columns match the ProbationRecord entity + BaseEntity.

CREATE TABLE probation_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT       NOT NULL,
    start_date        DATE         NOT NULL,
    end_date          DATE         NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'IN_PROBATION',
    confirmation_date DATE,
    decided_by        VARCHAR(190),
    decided_at        TIMESTAMPTZ,
    remarks           VARCHAR(500),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100),
    version           BIGINT       NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_probation_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_probation_employee ON probation_records (employee_id);
CREATE INDEX idx_probation_status   ON probation_records (status);
