-- Module 14: Employee Lifecycle. Columns match the entities + BaseEntity.

CREATE TABLE lifecycle_cases (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT       NOT NULL,
    type           VARCHAR(20)  NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'INITIATED',
    initiated_date DATE         NOT NULL,
    completed_date DATE,
    remarks        VARCHAR(500),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT       NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT fk_lifecycle_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_lifecycle_employee ON lifecycle_cases (employee_id);
CREATE INDEX idx_lifecycle_status   ON lifecycle_cases (status);

CREATE TABLE lifecycle_tasks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lifecycle_case_id BIGINT       NOT NULL,
    title             VARCHAR(200) NOT NULL,
    sequence          INTEGER      NOT NULL DEFAULT 0,
    completed         BOOLEAN      NOT NULL DEFAULT FALSE,
    completed_at      TIMESTAMPTZ,
    notes             VARCHAR(300),
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100),
    version           BIGINT       NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_lifecycle_tasks_case FOREIGN KEY (lifecycle_case_id) REFERENCES lifecycle_cases (id) ON DELETE CASCADE
);
CREATE INDEX idx_lifecycle_tasks_case ON lifecycle_tasks (lifecycle_case_id);
