-- Module 18: Automation Engine. Columns match the AutomationRule / AutomationRun entities + BaseEntity.
-- Rules are seeded idempotently at bootstrap by DataInitializer (one row per AutomationType).

CREATE TABLE automation_rules (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(40)   NOT NULL,
    enabled          BOOLEAN       NOT NULL DEFAULT TRUE,
    channels         VARCHAR(200)  NOT NULL DEFAULT '',
    title_template   VARCHAR(200)  NOT NULL,
    message_template VARCHAR(1000) NOT NULL,
    lead_days        INTEGER,
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    version          BIGINT        NOT NULL DEFAULT 0,
    is_deleted       BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT uk_automation_rules_type UNIQUE (type)
);

CREATE TABLE automation_runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id     BIGINT       NOT NULL,
    run_date    DATE         NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    manual      BOOLEAN      NOT NULL DEFAULT FALSE,
    matched     INTEGER      NOT NULL DEFAULT 0,
    dispatched  INTEGER      NOT NULL DEFAULT 0,
    detail      VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    version     BIGINT       NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT fk_automation_runs_rule FOREIGN KEY (rule_id) REFERENCES automation_rules (id) ON DELETE CASCADE
);
CREATE INDEX idx_automation_runs_rule_date ON automation_runs (rule_id, run_date);
CREATE INDEX idx_automation_runs_run_date  ON automation_runs (run_date);
