-- Module 19: Email Template Engine. Columns match the EmailTemplate entity + BaseEntity.
-- Starter templates are seeded idempotently at bootstrap by DataInitializer.

CREATE TABLE email_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100)  NOT NULL,
    name        VARCHAR(150)  NOT NULL,
    category    VARCHAR(30)   NOT NULL,
    subject     VARCHAR(300)  NOT NULL,
    body_html   TEXT          NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    description VARCHAR(300),
    created_at  TIMESTAMPTZ   NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    version     BIGINT        NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT uk_email_templates_code UNIQUE (code)
);
CREATE INDEX idx_email_templates_category ON email_templates (category);
