-- Module 20: WhatsApp Integration. Columns match the WhatsAppTemplate / WhatsAppMessage entities
-- + BaseEntity. Starter templates are seeded idempotently at bootstrap by DataInitializer.

CREATE TABLE whatsapp_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100)  NOT NULL,
    name        VARCHAR(150)  NOT NULL,
    category    VARCHAR(20)   NOT NULL,
    body_text   VARCHAR(1000) NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    description VARCHAR(300),
    created_at  TIMESTAMPTZ   NOT NULL,
    updated_at  TIMESTAMPTZ   NOT NULL,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    version     BIGINT        NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT uk_whatsapp_templates_code UNIQUE (code)
);
CREATE INDEX idx_whatsapp_templates_category ON whatsapp_templates (category);

CREATE TABLE whatsapp_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_phone            VARCHAR(20)   NOT NULL,
    recipient_id        BIGINT,
    template_code       VARCHAR(100),
    body                VARCHAR(1000) NOT NULL,
    status              VARCHAR(20)   NOT NULL,
    provider_message_id VARCHAR(100),
    failure_reason      VARCHAR(300),
    sent_at             TIMESTAMPTZ,
    delivered_at        TIMESTAMPTZ,
    read_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL,
    updated_at          TIMESTAMPTZ   NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    version             BIGINT        NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT fk_whatsapp_messages_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_whatsapp_messages_status      ON whatsapp_messages (status);
CREATE INDEX idx_whatsapp_messages_provider_id ON whatsapp_messages (provider_message_id);
