-- Module 23: Audit Logs. Append-only trail; columns match the AuditLog entity + BaseEntity.
-- The actor is denormalised (email + id, no FK) so the trail is immutable to user-record changes.

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(30)  NOT NULL,
    outcome     VARCHAR(10)  NOT NULL,
    module      VARCHAR(60),
    entity_type VARCHAR(60),
    entity_id   BIGINT,
    actor_email VARCHAR(190),
    actor_id    BIGINT,
    description VARCHAR(500),
    http_method VARCHAR(10),
    path        VARCHAR(300),
    status_code INTEGER,
    ip_address  VARCHAR(45),
    user_agent  VARCHAR(300),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    version     BIGINT       NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ
);
CREATE INDEX idx_audit_logs_action  ON audit_logs (action);
CREATE INDEX idx_audit_logs_actor   ON audit_logs (actor_email);
CREATE INDEX idx_audit_logs_module  ON audit_logs (module);
CREATE INDEX idx_audit_logs_created ON audit_logs (created_at);
