-- Module 2 (part 4): single-use account tokens for password reset and email verification.
-- Only the SHA-256 hash of each token is stored. Columns match BaseEntity + AccountToken.

CREATE TABLE account_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64)  NOT NULL,
    token_type VARCHAR(30)  NOT NULL,
    user_id    BIGINT       NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version    BIGINT       NOT NULL DEFAULT 0,
    is_deleted BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_account_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_account_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_account_tokens_user ON account_tokens (user_id);
