-- Module 3: company profile (single row) and the key/value system-settings store.
-- Columns match BaseEntity plus entity fields (Hibernate ddl-auto=validate).

CREATE TABLE company_profile (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name          VARCHAR(200) NOT NULL,
    display_name        VARCHAR(120) NOT NULL,
    registration_number VARCHAR(60),
    email               VARCHAR(190),
    phone               VARCHAR(30),
    website             VARCHAR(200),
    address_line1       VARCHAR(200),
    address_line2       VARCHAR(200),
    city                VARCHAR(100),
    state               VARCHAR(100),
    country             VARCHAR(100),
    postal_code         VARCHAR(20),
    timezone            VARCHAR(60),
    currency            VARCHAR(10),
    logo_url            VARCHAR(500),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    version             BIGINT       NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ
);

CREATE TABLE system_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(120)  NOT NULL,
    setting_value VARCHAR(2000),
    category      VARCHAR(80),
    description   VARCHAR(255),
    editable      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL,
    updated_at    TIMESTAMPTZ   NOT NULL,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    version       BIGINT        NOT NULL DEFAULT 0,
    is_deleted    BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT uk_system_settings_key UNIQUE (setting_key)
);
CREATE INDEX idx_system_settings_category ON system_settings (category);
