-- Module 4: Employee master. Column set matches the Employee entity and its embeddables
-- (contact/salary/bank/government-ids/social) plus BaseEntity. Hibernate ddl-auto=validate.

CREATE TABLE employees (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- personal
    employee_code       VARCHAR(40)  NOT NULL,
    full_name           VARCHAR(150) NOT NULL,
    gender              VARCHAR(20),
    date_of_birth       DATE,
    blood_group         VARCHAR(10),
    nationality         VARCHAR(60),
    marital_status      VARCHAR(20),
    photo_url           VARCHAR(500),
    -- contact (embedded)
    mobile              VARCHAR(30),
    personal_email      VARCHAR(190),
    official_email      VARCHAR(190),
    current_address     VARCHAR(300),
    permanent_address   VARCHAR(300),
    -- employment
    department_id       BIGINT,
    designation_id      BIGINT,
    employment_type_id  BIGINT,
    joining_date        DATE,
    end_date            DATE,
    notice_period_days  INTEGER,
    employment_status   VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    user_id             BIGINT,
    -- salary (embedded)
    basic_salary        NUMERIC(14,2),
    hra                 NUMERIC(14,2),
    special_allowance   NUMERIC(14,2),
    bonus               NUMERIC(14,2),
    incentives          NUMERIC(14,2),
    other_allowances    NUMERIC(14,2),
    -- bank (embedded)
    bank_name           VARCHAR(120),
    bank_account_number VARCHAR(40),
    bank_ifsc           VARCHAR(20),
    bank_account_holder VARCHAR(120),
    -- government ids (embedded)
    pan                 VARCHAR(20),
    aadhaar             VARCHAR(20),
    passport            VARCHAR(20),
    driving_license     VARCHAR(30),
    -- social (embedded)
    linkedin_url        VARCHAR(200),
    instagram_url       VARCHAR(200),
    facebook_url        VARCHAR(200),
    x_url               VARCHAR(200),
    -- audit (BaseEntity)
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    version             BIGINT       NOT NULL DEFAULT 0,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT uk_employees_code UNIQUE (employee_code),
    CONSTRAINT uk_employees_user UNIQUE (user_id),
    CONSTRAINT fk_employees_department      FOREIGN KEY (department_id)      REFERENCES departments (id),
    CONSTRAINT fk_employees_designation     FOREIGN KEY (designation_id)     REFERENCES designations (id),
    CONSTRAINT fk_employees_employment_type FOREIGN KEY (employment_type_id) REFERENCES employment_types (id),
    CONSTRAINT fk_employees_user            FOREIGN KEY (user_id)            REFERENCES users (id)
);
CREATE INDEX idx_employees_department  ON employees (department_id);
CREATE INDEX idx_employees_designation ON employees (designation_id);
CREATE INDEX idx_employees_status      ON employees (employment_status);
