-- Module 4 (part 2): employee child collections + timeline. Each table is keyed by employee_id
-- (ON DELETE CASCADE) and carries the BaseEntity audit/version/soft-delete columns.

CREATE TABLE employee_emergency_contacts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT       NOT NULL,
    name            VARCHAR(150) NOT NULL,
    relationship    VARCHAR(60),
    phone           VARCHAR(30),
    alternate_phone VARCHAR(30),
    email           VARCHAR(190),
    address         VARCHAR(300),
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    version         BIGINT       NOT NULL DEFAULT 0,
    is_deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT fk_emergency_contacts_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_emergency_contacts_employee ON employee_emergency_contacts (employee_id);

CREATE TABLE employee_family_members (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL,
    name          VARCHAR(150) NOT NULL,
    relationship  VARCHAR(60),
    date_of_birth DATE,
    occupation    VARCHAR(120),
    phone         VARCHAR(30),
    dependent     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    version       BIGINT       NOT NULL DEFAULT 0,
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT fk_family_members_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_family_members_employee ON employee_family_members (employee_id);

CREATE TABLE employee_education (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT       NOT NULL,
    institution    VARCHAR(200) NOT NULL,
    degree         VARCHAR(150),
    field_of_study VARCHAR(150),
    start_year     INTEGER,
    end_year       INTEGER,
    grade          VARCHAR(60),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT       NOT NULL DEFAULT 0,
    is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT fk_employee_education_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_employee_education_employee ON employee_education (employee_id);

CREATE TABLE employee_experience (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  BIGINT       NOT NULL,
    company_name VARCHAR(200) NOT NULL,
    designation  VARCHAR(150),
    from_date    DATE,
    to_date      DATE,
    description  VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    version      BIGINT       NOT NULL DEFAULT 0,
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT fk_employee_experience_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_employee_experience_employee ON employee_experience (employee_id);

CREATE TABLE employee_timeline_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT       NOT NULL,
    event_type  VARCHAR(30)  NOT NULL,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    event_date  DATE         NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    version     BIGINT       NOT NULL DEFAULT 0,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT fk_timeline_events_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_timeline_events_employee ON employee_timeline_events (employee_id);
