-- Module 5: Document Management. Metadata table; binary content lives in the storage backend.
-- Columns match the Document entity + BaseEntity (Hibernate ddl-auto=validate).

CREATE TABLE documents (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type     VARCHAR(40)  NOT NULL,
    employee_id       BIGINT,
    title             VARCHAR(200) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type      VARCHAR(120),
    size_bytes        BIGINT,
    storage_key       VARCHAR(400) NOT NULL,
    folder            VARCHAR(200),
    description       VARCHAR(500),
    expiry_date       DATE,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100),
    version           BIGINT       NOT NULL DEFAULT 0,
    is_deleted        BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT uk_documents_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_documents_employee FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE
);
CREATE INDEX idx_documents_employee ON documents (employee_id);
CREATE INDEX idx_documents_type     ON documents (document_type);
